apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: ecr-container
        image: drwkwxuexi/backend-feed:latest
        ports:
          - containerPort: 80
        env:
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: AWS_DEFAULT_REGION
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: AWS_BUCKET
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: AWS_REGION
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: AWS_PROFILE
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: URL
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: POSTGRES_DB

          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: AWS_SECRET_ACCESS_KEY
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: POSTGRES_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: JWT_SECRET
