apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: ecr-container
        image: 823860120474.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        ports:
        - containerPort: 80
