apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: ecr-container
        image: 823860120474.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
        ports:
        - containerPort: 8080
