name: Build and Deploy to EKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Build:
    name: Build Frontend and Backend and Upload to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Frontend
        working-directory: udagram-frontend
        run: |
          GIT_HASH=$(git rev-parse --short HEAD) 
          docker build -t frontend:${GIT_HASH} .

      - name: Build Backend
        working-directory: api
        run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          docker build -t backend:${GIT_HASH} .

      - name: Login to ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 367479749599.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Push Frontend image
        run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          docker tag frontend:${GIT_HASH} 823860120474.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_FRONT }}:${GIT_HASH}
          docker push 823860120474.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_FRONT }}:${GIT_HASH}

      - name: Push Backend image
        run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          docker tag backend:${GIT_HASH} 823860120474.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_BACK }}:${GIT_HASH}
          docker push 823860120474.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_BACK }}:${GIT_HASH}



